# Generated by Django 4.1.5 on 2023-02-10 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_selection'),
    ]

    operations = [
        migrations.RenameField(
            model_name='selection',
            old_name='mame',
            new_name='name',
        ),
    ]
